# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  catalogdb:
    image: postgres

volumes:
  postgres_catalog: